# Generated by Django 4.0.2 on 2022-04-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Categories', '0004_sub_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=250)),
                ('meta', models.TextField(blank=True, max_length=500, null=True)),
                ('descriptions', models.TextField(blank=True, max_length=500, null=True)),
                ('alter_text', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('feature_image', models.ImageField(upload_to='media')),
                ('category', models.ManyToManyField(to='Categories.Categories')),
                ('sub_category', models.ManyToManyField(to='Categories.Sub_Categories')),
            ],
        ),
    ]
