# Generated by Django 4.0.2 on 2022-04-22 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductInventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='media')),
                ('property', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ProductInventory.products')),
            ],
        ),
    ]
