# Generated by Django 4.0.2 on 2022-04-22 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0002_sub_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sub_Categories',
        ),
    ]
